package k8sexec

import (
	"bufio"
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"slices"
	"sort"
	"strings"
	"time"

	v1 "k8s.io/api/apps/v1"
	batchv1 "k8s.io/api/batch/v1"
	coreV1 "k8s.io/api/core/v1"
	metaV1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/httpstream"
	"k8s.io/apimachinery/pkg/util/net"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/kubernetes/scheme"

	// these two client's plugins are not necessary for Nokia but added to have complete support
	_ "k8s.io/client-go/plugin/pkg/client/auth/azure"
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"

	// oidc plugin is used in Nokia labs
	_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/tools/remotecommand"
	"k8s.io/client-go/util/exec"
)

// ExecutionStatus encapsulates the result and details of executing a command within a specific container.
// It includes both identification and outcome information. The container is specified by its name and
// the associated pod's name, provided in the Container and Pod fields, respectively.
// The execution outcome is detailed as follows:
// - RetCode: The exit code of the command executed within the container. A zero value typically indicates success.
// - Error: A string representation of any error that occurred during command execution, as reported by the Kubernetes API.
// - Stdout: The standard output generated by the command.
// - Stderr: The standard error output generated by the command, if any.
type ExecutionStatus struct {
	Namespace string    `json:"Namespace"`
	Pod       string    `json:"Pod"`
	Container string    `json:"Container"`
	RetCode   ExitCode  `json:"RetCode"`
	Error     []string  `json:"Error"`
	Stdout    []string  `json:"Stdout"`
	Stderr    []string  `json:"Stderr"`
	ExecTime  time.Time `json:"ExecTime"`
}

// String returns a formatted string representation of an ExecutionStatus instance detailing execution parameters and results.
func (e *ExecutionStatus) String() string {
	stdout := strings.Join(e.Stdout, "\n")
	if len(stdout) > 80 {
		stdout = stdout[:80] + "..."
	}
	stderr := strings.Join(e.Stderr, "\n")
	if len(stderr) > 80 {
		stderr = stderr[:80] + "..."
	}

	return fmt.Sprintf("Namespace: %s, Pod: %s, Container: %s, RetCode: %d, Error: %s, Stdout: %s, Stderr: %s, ExecTime: %s",
		e.Namespace, e.Pod, e.Container, e.RetCode, strings.Join(e.Error, "\n"), stdout, stderr, e.ExecTime)
}

// String returns a formatted string representation of an ExecutionStatus instance detailing execution parameters and results.
func (e *ExecutionStatus) Raw() string {
	return fmt.Sprintf("Namespace: %s, Pod: %s, Container: %s, RetCode: %d, Error: %s, Stdout: %s, Stderr: %s, ExecTime: %s",
		e.Namespace, e.Pod, e.Container, e.RetCode, strings.Join(e.Error, "\n"), strings.Join(e.Stdout, "\n"), strings.Join(e.Stderr, "\n"), e.ExecTime)
}

// K8SExec defines the context for modules executing commands in Kubernetes environments.
// It includes details necessary for operations, such as cluster configuration, target pod and container,
// and authentication credentials, facilitating effective interaction with Kubernetes resources.
type K8SExec struct {
	Config    *rest.Config
	Clientset *kubernetes.Clientset
}

// ExitCode is an enumeration of possible exit codes with descriptive names.
// It provides a more idiomatic way to refer to exit codes within the Go application.
type ExitCode int

const (
	NotExecutedDueToRoot ExitCode = iota - 4
	ManualAssessmentNeeded
	ExecutionTimeOut
	InternalAppError
	Success
	GeneralError
	IncorrectUsageExitCode
	CommandCannotExecute  ExitCode = 126
	CommandNotFound       ExitCode = 127
	InvalidArgumentToExit ExitCode = 128
	// Skips to specific values after the iota increment
	ScriptTerminatedByControlC ExitCode = 130
	ExitStatusOutOfRange       ExitCode = 255
	// Signal based exit codes (128+n)
	FatalErrorSignal1 ExitCode = 129
	// FatalErrorSignal2 is omitted as it overlaps with ScriptTerminatedByControlC
	FatalErrorSignal3  ExitCode = 131
	FatalErrorSignal4  ExitCode = 132
	FatalErrorSignal5  ExitCode = 133
	FatalErrorSignal6  ExitCode = 134
	FatalErrorSignal7  ExitCode = 135
	FatalErrorSignal8  ExitCode = 136
	FatalErrorSignal9  ExitCode = 137
	FatalErrorSignal10 ExitCode = 138
	FatalErrorSignal11 ExitCode = 139
	FatalErrorSignal12 ExitCode = 140
	FatalErrorSignal13 ExitCode = 141
	FatalErrorSignal14 ExitCode = 142
	FatalErrorSignal15 ExitCode = 143
)

func (e ExitCode) String() string {
	if _, ok := exitCodeDescriptions[e]; !ok {
		return fmt.Sprintf("%d", e)
	}
	return exitCodeDescriptions[e]
}

// exitCodeDescriptions maps possible exit codes with descriptive names.
var exitCodeDescriptions map[ExitCode]string = map[ExitCode]string{
	-1:  "Internal app error",
	-2:  "Execution time out",
	-3:  "Manual assessment needed",
	-4:  "Not executed due to root",
	0:   "Success",
	1:   "General error, unspecified error",
	2:   "Incorrect usage or syntax of the command",
	126: "Command cannot execute",
	127: "Command not found",
	128: "Invalid argument to exit",
	130: "Script terminated by Control-C (SIGINT)",
	255: "Exit status out of range",
	// Signal based exit codes (128+n)
	129: "Fatal error signal 1 (SIGHUP)",
	//130: "Fatal error signal 2 (SIGINT)",
	131: "Fatal error signal 3 (SIGQUIT)",
	132: "Fatal error signal 4 (SIGILL)",
	133: "Fatal error signal 5 (SIGTRAP)",
	134: "Fatal error signal 6 (SIGABRT/SIGIOT)",
	135: "Fatal error signal 7 (SIGBUS)",
	136: "Fatal error signal 8 (SIGFPE)",
	137: "Fatal error signal 9 (SIGKILL)",
	138: "Fatal error signal 10 (SIGUSR1)",
	139: "Fatal error signal 11 (SIGSEGV)",
	140: "Fatal error signal 12 (SIGUSR2)",
	141: "Fatal error signal 13 (SIGPIPE)",
	142: "Fatal error signal 14 (SIGALRM)",
	143: "Fatal error signal 15 (SIGTERM)",
}

// GetExitCode returns an ExitCode retrieved from CodeExitError type returned by k8s.io/client-go/util/exec and
// a corresponding description from exitCodeDescriptions map.
func GetExitCode(err error) (ExitCode, string) {
	var e exec.CodeExitError
	if !errors.As(err, &e) {
		return InternalAppError, ""
	}
	if _, ok := exitCodeDescriptions[ExitCode(e.Code)]; !ok {
		return ExitCode(e.Code), fmt.Sprintf("Exit code %d description not found!", e.Code)
	}
	return ExitCode(e.Code), exitCodeDescriptions[ExitCode(e.Code)]
}

// GetExitCodeDescription returns a string description for a given exit code.
// It looks up the code in the predefined exitCodeDescriptions map. If the code is found,
// it returns the corresponding description. If not, it returns "Unknown exit code".
func GetExitCodeDescription(code ExitCode) string {
	if _, ok := exitCodeDescriptions[code]; !ok {
		return fmt.Sprintf("%d", code)
	}
	return exitCodeDescriptions[code]
}

// NewK8SExec creates and initializes an instance of the K8SExec type.
// It takes Kubernetes configuration information as parameters, which are required
// to access and interact with the Kubernetes cluster. This function ensures that
// the created K8SExec instance is ready to use for executing commands within Kubernetes
// pods and containers, by embedding necessary configuration details.
func NewK8SExec(kubeconfig string) (info *K8SExec, err error) {
	config, err := clientcmd.BuildConfigFromFlags("", kubeconfig)
	if err != nil {
		return nil, err
	}

	config.QPS = 100
	config.Burst = 200
	config.Timeout = 0

	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		return nil, err
	}

	return &K8SExec{
		Config:    config,
		Clientset: clientset,
	}, nil
}

func (k8s *K8SExec) Clone() (*K8SExec, error) {
	copied := rest.CopyConfig(k8s.Config)
	clientset, err := kubernetes.NewForConfig(copied)
	if err != nil {
		return nil, err
	}
	return &K8SExec{
		Config:    copied,
		Clientset: clientset,
	}, nil
}

// GetClientset returns the Kubernetes clientset associated with the K8SExec instance.
func (k8s *K8SExec) GetClientset() *kubernetes.Clientset {
	return k8s.Clientset
}

// GetConfig returns the Kubernetes REST configuration associated with the K8SExec instance.
func (k8s *K8SExec) GetConfig() *rest.Config {
	return k8s.Config
}

// GetAllNamespaces retrieves a list of all namespace names in the Kubernetes cluster.
func (k8s *K8SExec) GetAllNamespaces(ctx context.Context) ([]string, error) {
	list, err := k8s.Clientset.CoreV1().Namespaces().List(ctx, metaV1.ListOptions{})
	if err != nil {
		return nil, err
	}
	var namespaces []string
	for _, ns := range list.Items {
		namespaces = append(namespaces, ns.GetName())
	}
	return namespaces, nil
}

// GetJobs retrieves all Jobs within the namespace specified by the 'k8s' context.
// This function utilizes the Kubernetes client-go library to fetch a list of Jobs
// from the specified namespace, facilitating the management and interaction with
// Kubernetes resources. It returns a list of Jobs and any error encountered during
// the retrieval process.
func (k8s *K8SExec) GetJobs(ctx context.Context, namespace string, options metaV1.ListOptions) ([]batchv1.Job, error) {
	// Retrieve jobs in the "default" namespace
	jobs, err := k8s.Clientset.BatchV1().Jobs(namespace).List(ctx, options)
	if err != nil {
		return nil, err
	}
	return jobs.Items, nil
}

// GetPod retrieves a Pod based on its name within the specified namespace.
// The namespace is provided by the 'k8s' context. This function simplifies the process
// of locating a specific Pod within a namespace, leveraging the Kubernetes client-go
// library to interact with the Kubernetes API. It returns the found Pod and any error
// encountered during the retrieval process.
func (k8s *K8SExec) GetPod(ctx context.Context, namespace string, podName string) (*coreV1.Pod, error) {
	pod, err := k8s.Clientset.CoreV1().Pods(namespace).Get(ctx, podName, metaV1.GetOptions{})
	if err != nil {
		return nil, err
	}
	return pod, nil
}

// GetPodContainers retrieves a list of containers associated with a given Pod.
// It leverages the Kubernetes client-go library to query the Kubernetes API for Pod containers,
// facilitating the retrieval of container information for a given Pod.
func (k8s *K8SExec) GetPodContainers(ctx context.Context, namespace string, podName string) ([]coreV1.Container, error) {
	pod, err := k8s.GetPod(ctx, namespace, podName)
	if err != nil {
		return nil, err
	}
	return pod.Spec.Containers, nil
}

// GetPodContainer retrieves a specific container associated with a given Pod.
// It leverages the Kubernetes client-go library to query the Kubernetes API for Pod containers,
// facilitating the retrieval of container information for a given Pod.
func (k8s *K8SExec) GetPodContainer(ctx context.Context, namespace string, podName string, containerName string) (*coreV1.Container, error) {
	pod, err := k8s.GetPod(ctx, namespace, podName)
	if err != nil {
		return nil, err
	}
	for _, container := range pod.Spec.Containers {
		if container.Name == containerName {
			return &container, nil
		}
	}
	return nil, fmt.Errorf("container %s not found in pod %s", containerName, podName)
}

// GetPodDefaultContainer retrieves the default container associated with a given Pod.
// It leverages the Kubernetes client-go library to query the Kubernetes API for Pod containers,
// facilitating the retrieval of container information for a given Pod.
func (k8s *K8SExec) GetPodDefaultContainer(ctx context.Context, namespace string, podName string) (*coreV1.Container, error) {
	pod, err := k8s.GetPod(ctx, namespace, podName)
	if err != nil {
		return nil, err
	}

	// Check for the specific annotation
	if defaultName, ok := pod.ObjectMeta.Annotations["kubectl.kubernetes.io/default-container"]; ok {
		for _, container := range pod.Spec.Containers {
			if container.Name == defaultName {
				return &container, nil
			}
		}
	}
	if len(pod.Spec.Containers) > 0 {
		return &pod.Spec.Containers[0], nil
	}
	return nil, fmt.Errorf("no default container found")
}

// GetPods retrieves all Pods within the namespace specified by the 'k8s' context.
// This function utilizes the Kubernetes client-go library to fetch a list of Pods
// from the specified namespace, facilitating the management and interaction with
// Kubernetes resources. It returns a list of Pods and any error encountered during
// the retrieval process.
func (k8s *K8SExec) GetPods(ctx context.Context, namespace string, options metaV1.ListOptions) ([]coreV1.Pod, error) {
	var pods *coreV1.PodList
	pods, err := k8s.Clientset.CoreV1().Pods(namespace).List(ctx, options)
	if err != nil {
		return nil, err
	}
	return pods.Items, nil
}

// GetDeployments retrieves all Deployments within the namespace specified in the 'k8s' context.
// It leverages the Kubernetes client-go library to query the Kubernetes API for Deployments,
// aiming to streamline the process of managing Kubernetes resources.
// This function returns an array of Deployments along with any error encountered during the query,
// thus enabling comprehensive oversight of Deployment resources within the designated namespace.
func (k8s *K8SExec) GetDeployments(ctx context.Context, namespace string) (*v1.DeploymentList, error) {
	var deployments *v1.DeploymentList
	deployments, err := k8s.Clientset.AppsV1().Deployments(namespace).List(ctx, metaV1.ListOptions{})
	if err != nil {
		return nil, err
	}
	return deployments, nil
}

// GetStatefulSets fetches all StatefulSets within the specified namespace, as determined by the 'k8s' context.
// Utilizing the client-go library, this function communicates with the Kubernetes API to gather StatefulSets,
// facilitating detailed management and operational oversight of these specific Kubernetes resources.
// It returns a collection of StatefulSets and any errors encountered in the process, ensuring comprehensive
// access to StatefulSet configurations within the given namespace.
func (k8s *K8SExec) GetStatefulSets(ctx context.Context, namespace string) (*v1.StatefulSetList, error) {
	var statefulSets *v1.StatefulSetList
	statefulSets, err := k8s.Clientset.AppsV1().StatefulSets(namespace).List(ctx, metaV1.ListOptions{})
	if err != nil {
		return nil, err
	}
	return statefulSets, nil
}

// GetDaemonSets fetches all DaemonSets within the specified namespace, as determined by the 'k8s' context.
// Utilizing the client-go library, this function communicates with the Kubernetes API to gather DaemonSets,
// facilitating detailed management and operational oversight of these specific Kubernetes resources.
// It returns a collection of StatefulSets and any errors encountered in the process, ensuring comprehensive
// access to StatefulSet configurations within the given namespace.
func (k8s *K8SExec) GetDaemonSets(ctx context.Context, namespace string) (*v1.DaemonSetList, error) {
	var daemonSets *v1.DaemonSetList
	daemonSets, err := k8s.Clientset.AppsV1().DaemonSets(namespace).List(ctx, metaV1.ListOptions{})
	if err != nil {
		return nil, err
	}
	return daemonSets, nil
}

// GetConfigmaps fetches all ConfigMaps within the specified namespace, as determined by the 'k8s' context.
// Utilizing the client-go library, this function communicates with the Kubernetes API to gather ConfigMaps,
// returning a collection of ConfigMap resources and any errors encountered during the process.
func (k8s *K8SExec) GetConfigmaps(ctx context.Context, namespace string) (*coreV1.ConfigMapList, error) {
	var configMaps *coreV1.ConfigMapList
	configMaps, err := k8s.Clientset.CoreV1().ConfigMaps(namespace).List(ctx, metaV1.ListOptions{})
	if err != nil {
		return nil, err
	}
	return configMaps, nil
}

func score(p *coreV1.Pod) int {
	switch {
	case p.DeletionTimestamp != nil:
		return 0 // being torn down; may vanish before you reach it
	case hasRunningContainer(p):
		return 3 // inspectable
	case p.Status.Phase == coreV1.PodRunning:
		return 2 // Running but nothing live — CrashLoopBackOff
	case p.Status.Phase == coreV1.PodPending:
		return 1
	default:
		return 0
	}
}

func hasRunningContainer(p *coreV1.Pod) bool {
	for i := range p.Status.ContainerStatuses {
		if p.Status.ContainerStatuses[i].State.Running != nil {
			return true
		}
	}
	return false
}

func preferredPod(pod, cur *coreV1.Pod) *coreV1.Pod {
	if sp, sc := score(pod), score(cur); sp != sc {
		if sp > sc {
			return pod
		}
		return cur
	}
	if pod.CreationTimestamp.After(cur.CreationTimestamp.Time) {
		return pod
	}
	if pod.CreationTimestamp.Equal(&cur.CreationTimestamp) && pod.Name < cur.Name {
		return pod
	}
	return cur
}

// GetPods retrieves a comprehensive and unique list of Pods within a given namespace,
// as provided by the 'k8s' context.
func (k8s *K8SExec) GetUniquePods(ctx context.Context, namespace string) (int, []*coreV1.Pod, error) {

	podsList, err := k8s.Clientset.CoreV1().Pods(namespace).List(ctx, metaV1.ListOptions{FieldSelector: "status.phase!=Succeeded,status.phase!=Failed"})
	if err != nil {
		return 0, nil, err
	}
	var notOwnedPods []*coreV1.Pod
	var ownedPods map[types.UID]*coreV1.Pod = make(map[types.UID]*coreV1.Pod)

	for i := range podsList.Items {
		pod := &podsList.Items[i]
		owner := metaV1.GetControllerOf(pod)
		if owner == nil {
			notOwnedPods = append(notOwnedPods, pod)
			continue
		}
		if cur, ok := ownedPods[owner.UID]; ok {
			preferred := preferredPod(pod, cur)
			ownedPods[owner.UID] = preferred
			continue
		}
		ownedPods[owner.UID] = pod
	}

	uniquePods := make([]*coreV1.Pod, 0, len(ownedPods))
	for _, pod := range ownedPods {
		uniquePods = append(uniquePods, pod)
	}

	uniquePods = append(uniquePods, notOwnedPods...)
	sort.Slice(uniquePods, func(i, j int) bool { return uniquePods[i].Name < uniquePods[j].Name })
	return len(podsList.Items), uniquePods, nil
}

// GetUniqueImages retrieves a comprehensive and unique list of Pods within a given namespace,
// as provided by the 'k8s' context. It targets Pods associated with Deployments, StatefulSets,
// and those directly within the namespace, ensuring no duplicates.
func (k8s *K8SExec) GetUniqueImages(ctx context.Context, namespace string) (int, []string, error) {
	var images []string
	var containersCount int

	podsList, err := k8s.Clientset.CoreV1().Pods(namespace).List(ctx, metaV1.ListOptions{})
	if err != nil {
		return 0, nil, err
	}

	for _, pod := range podsList.Items {
		containersCount += len(pod.Spec.Containers)
		for _, container := range pod.Spec.Containers {
			if slices.Contains(images, container.Image) {
				continue
			}
			images = append(images, container.Image)
		}
	}

	return containersCount, images, nil
}

// GetLogs retrieves the logs from the specified pod and container within the Kubernetes namespace of the K8SExec instance.
// It returns the size of the logs in bytes, the log data as a byte slice, and an error if the operation fails.
func (k8s *K8SExec) GetLogs(ctx context.Context, namespace string, podName string, containerName string) (int, []byte, error) {
	// Request logs
	opt := new(coreV1.PodLogOptions)
	opt.Container = containerName
	req := k8s.Clientset.CoreV1().Pods(namespace).GetLogs(podName, opt)

	// Read log stream
	logReader, err := req.Stream(ctx)
	if err != nil {
		return 0, nil, err
	}
	defer logReader.Close()

	//runtime.ErrorHandlers = []runtime.ErrorHandler{
	//	func(ctx context.Context, err error, msg string, keysAndValues ...interface{}) {
	//		// ignore unhandled errors
	//		if errors.Is(err, io.EOF) || errors.Is(err, io.ErrClosedPipe) || errors.Is(err, io.ErrUnexpectedEOF) {
	//			return
	//		}
	//
	//	},
	//}

	buf := new(bytes.Buffer)
	r := bufio.NewReader(logReader)
	for {
		data, err := r.ReadBytes('\n')
		if err != nil {
			if !errors.Is(err, io.EOF) && !errors.Is(err, io.ErrClosedPipe) && !errors.Is(err, io.ErrUnexpectedEOF) {
				return 0, nil, err
			}
			break
		}
		if _, err := buf.Write(data); err != nil {
			return 0, nil, err
		}
	}

	return buf.Len(), buf.Bytes(), nil
}

func (k8s *K8SExec) ReadFile(ctx context.Context, namespace string, podName, containerName string, filePath string) (string, error) {
	var stdout, stderr bytes.Buffer
	var cancelFunc context.CancelFunc

	ctx, cancelFunc = context.WithTimeout(ctx, 5*time.Second)
	defer cancelFunc()

	retCode, err := k8s.exec(ctx, namespace, podName, containerName, []string{"cat", filePath}, nil, &stdout, &stderr, false)
	if retCode != Success {
		stdout.Reset()
		stderr.Reset()
		retCode, err = k8s.exec(ctx, namespace, podName, containerName, []string{"sed", "", filePath}, nil, &stdout, &stderr, false)
	}
	if retCode != Success {
		stdout.Reset()
		stderr.Reset()
		retCode, err = k8s.exec(ctx, namespace, podName, containerName, []string{"tail", "-n", "+1", filePath}, nil, &stdout, &stderr, false)
	}
	if retCode != Success {
		stdout.Reset()
		stderr.Reset()
		command := []string{
			"sh", "-c",
			`while IFS= read -r line; do echo "$line"; done < "$0"`,
			filePath,
			//fmt.Sprintf("while IFS= read -r line; do echo \"$line\"; done < '%s'", filePath),
		}
		retCode, err = k8s.exec(ctx, namespace, podName, containerName, command, nil, &stdout, &stderr, false)
	}
	return stdout.String(), err
}

// CheckIfFilePathIsReadable determines if a file at the given path in a specified container and pod is readable.
func (k8s *K8SExec) CheckIfFilePathIsReadable(ctx context.Context, namespace string, podName, containerName string, filePath string) bool {
	var stdout, stderr bytes.Buffer
	ctx, cancelFunc := context.WithTimeout(ctx, 5*time.Second)
	defer cancelFunc()

	retCode, _ := k8s.exec(ctx, namespace, podName, containerName, []string{"stat", "-c", "%a", filePath}, nil, &stdout, &stderr, false)

	// stat failed, let's try 'test -r'
	if retCode != Success {
		retCode, _ = k8s.exec(ctx, namespace, podName, containerName, []string{"sh", "-c", `test -r "$0"`, filePath}, nil, &stdout, &stderr, false)

		return retCode == Success
	}

	// stat was successful so let's analyze permissions
	permStr := strings.TrimSpace(stdout.String())
	if len(permStr) >= 3 {
		if len(permStr) == 4 {
			permStr = permStr[1:]
		}

		ownerPerm := int(permStr[0] - '0')
		groupPerm := int(permStr[1] - '0')
		othersPerm := int(permStr[2] - '0')
		const readBit = 4

		return ownerPerm&readBit != 0 || groupPerm&readBit != 0 || othersPerm&readBit != 0
	}

	return false
}

func (k8s *K8SExec) CheckIfFilePathExists(namespace string, podName, containerName string, filePath string) bool {
	var stdout, stderr bytes.Buffer
	ctx, cancelFunc := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancelFunc()

	retCode, _ := k8s.exec(ctx, namespace, podName, containerName, []string{"stat", filePath}, nil, &stdout, &stderr, false)
	if retCode != Success {
		retCode, _ = k8s.exec(ctx, namespace, podName, containerName, []string{"sh", "-c", fmt.Sprintf("[ -f '%s' ]", filePath)}, nil, &stdout, &stderr, false)
	}

	return retCode == Success
}

// exec executes a command provided via standard input ('stdin'), command-line arguments ('cmd'),
// or both, offering a versatile interface for command execution. Upon completion, it returns a POSIX
// execution code to indicate the success or failure of the operation, alongside any error encountered
// during execution for detailed diagnostics. Additionally, the function captures and returns both
// the standard output ('stdout') and standard error ('stderr') streams, providing details of the command's execution.
func (k8s *K8SExec) exec(ctx context.Context, namespace string, podName string, containerName string, cmd []string, stdin io.Reader, stdout io.Writer, stderr io.Writer, tty bool) (ExitCode, error) {
	req := k8s.Clientset.CoreV1().RESTClient().
		Post().
		Resource("pods").
		Name(podName).
		Namespace(namespace).
		SubResource("exec").
		VersionedParams(&coreV1.PodExecOptions{
			Container: containerName,
			Command:   cmd,
			Stdin:     stdin != nil,
			Stdout:    stdout != nil,
			Stderr:    stderr != nil,
			TTY:       tty,
		}, scheme.ParameterCodec)

	spdyExecutor, err := remotecommand.NewSPDYExecutor(k8s.Config, "POST", req.URL())
	if err != nil {
		return InternalAppError, fmt.Errorf("failed to create SPDY executor: %w", err)
	}

	// WebSockets strictly use GET for the HTTP upgrade handshake
	wsExecutor, err := remotecommand.NewWebSocketExecutor(k8s.Config, "GET", req.URL().String())
	if err != nil {
		return InternalAppError, fmt.Errorf("failed to create WebSocket executor: %w", err)
	}

	// This attempts WebSockets first. If the server rejects the upgrade (e.g., an older
	// Kubernetes version), it evaluates the fallback condition and drops down to SPDY.
	executor, err := remotecommand.NewFallbackExecutor(wsExecutor, spdyExecutor, func(err error) bool {
		// httpstream.IsUpgradeFailure checks if the error indicates the server doesn't support the protocol
		return httpstream.IsUpgradeFailure(err)
	})
	if err != nil {
		return InternalAppError, fmt.Errorf("failed to create fallback executor: %w", err)
	}

	err = executor.StreamWithContext(ctx, remotecommand.StreamOptions{
		Stdin:  stdin,
		Stdout: stdout,
		Stderr: stderr,
		Tty:    tty,
	})

	codeExitError := exec.CodeExitError{}

	switch {
	case err == nil:
		return Success, nil
	case errors.As(err, &codeExitError):
		code := codeExitError.ExitStatus()
		if code == 126 {
			// permission denied / not executable
			return CommandCannotExecute, err
		}
		if code == 127 { // some runtimes report not-found this way
			return CommandNotFound, err
		}
		return ExitCode(code), codeExitError
	default:
		return InternalAppError, err
	}
}

// DirectExec executes a command inside a specified container of a pod, with I/O streams and TTY access if enabled.
func (k8s *K8SExec) DirectExec(ctx context.Context, namespace string, podName string, containerName string, cmd []string, stdin io.Reader, stdout io.Writer, stderr io.Writer, tty bool) (ExitCode, error) {
	return k8s.exec(ctx, namespace, podName, containerName, cmd, stdin, stdout, stderr, tty)
}

// NewExecutionStatus initializes a new instance of the ExecutionStatus type, providing a method
// to encapsulate the outcome of a command's execution within a structured format.
// This function serves as a constructor, setting up an ExecutionStatus instance.
func NewExecutionStatus(namespace string, pod string, container string, retCode ExitCode, error string, stdout string, stderr string, execTime time.Time) *ExecutionStatus {
	return &ExecutionStatus{Namespace: namespace, Pod: pod, Container: container, RetCode: retCode, Error: strings.Split(error, "\n"), Stdout: strings.Split(stdout, "\n"), Stderr: strings.Split(stderr, "\n"), ExecTime: execTime}
}

// Exec executes a command provided through standard input ('stdin') or as arguments ('args'),
// or a combination of both. This function returns a pointer to an instance of ExecutionStatus,
// which encapsulates the results of the command execution. This includes details such as the exit code,
// error messages, and the outputs captured from both the standard output and standard error streams.
// timeout has to be provided as time.Duration.
func (k8s *K8SExec) Exec(namespace string, podName string, containerName string, args []string, stdin io.Reader, timeout time.Duration) *ExecutionStatus {
	var stdout, stderr bytes.Buffer
	var errMessage string

	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	execTime := time.Now()
	retCode, err := k8s.exec(ctx, namespace, podName, containerName, args, stdin, &stdout, &stderr, false)
	if err != nil {
		errMessage = err.Error()
	}

	if net.IsTimeout(err) || errors.Is(err, context.DeadlineExceeded) {
		retCode = ExecutionTimeOut
	}
	return NewExecutionStatus(namespace, podName, containerName, retCode, errMessage, stdout.String(), stderr.String(), execTime)
}

// ExecWithContext executes a command provided through standard input ('stdin') or as arguments ('args'),
// or a combination of both. This function returns a pointer to an instance of ExecutionStatus,
// which encapsulates the results of the command execution. This includes details such as the exit code,
// error messages, and the outputs captured from both the standard output and standard error streams.
// The use of this function must provide a context that will govern the command exeuction.
func (k8s *K8SExec) ExecWithContext(ctx context.Context, namespace string, podName string, containerName string, args []string, stdin io.Reader) *ExecutionStatus {
	var stdout, stderr bytes.Buffer
	var errMessage string

	execTime := time.Now()
	retCode, err := k8s.exec(ctx, namespace, podName, containerName, args, stdin, &stdout, &stderr, false)
	if err != nil {
		errMessage = err.Error()
	}

	if net.IsTimeout(err) || errors.Is(err, context.DeadlineExceeded) {
		retCode = ExecutionTimeOut
	}

	return NewExecutionStatus(namespace, podName, containerName, retCode, errMessage, stdout.String(), stderr.String(), execTime)
}
